### ISSUE TITLE
Up to Date?

### ISSUE THREAD

**Issue by nronnei** [del-dom/Geo821Project#2]
Hey Dom,

Just wanted to ask if the repo contains your most up-to-date rendition of the map?  Was gonna put in a little work on it, and wanted to make sure I wasn't working on day old bread ;)

**Comment by del-dom** [comment]
It does have the most up to date version. But, I talked to Jim over the
weekend and they are going to collect some more data and wanted to do
something a little more robust (some layer toggles and a few other little
things).I said I would put that together for them after the semester ends
that way they have plenty of time to collect the data. So, if you want to
wait and we can collaborate on something a little heartier in June I think
that would be the best plan.

-Dom

On Mon, Apr 11, 2016 at 4:07 PM, Nick Ronnei notifications@github.com
wrote:

> Hey Dom,
> 
> Just wanted to ask if the repo contains your most up-to-date rendition of
> the map? Was gonna put in a little work on it, and wanted to make sure I
> wasn't working on day old bread ;)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/del-dom/Geo821Project/issues/2

## 

Dominick Del Ponte
_Graduate Student_
_Department of Geography_
_Research Assistant_
_Global Observatory for Ecosystem Services_
Michigan State University
_delponte@msu.edu delponte@msu.edu_

**Comment by nronnei** [comment]
Sounds great, looking forward to it. Just gonna do some real basic stuff like filling out the directory structure and setting more explicit map options.
